"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {defaultDays} from "../lib/defaultData";
import {loadDays,resetDays,saveDays} from "../lib/storage";
import {TripDay} from "../lib/types";
const AUTH="stone-trips-admin-stage3";
export default function AdminAllDays(){
 const [auth,setAuth]=useState(false),[password,setPassword]=useState(""),[error,setError]=useState(""),[saved,setSaved]=useState(false);
 const [days,setDays]=useState<TripDay[]>(defaultDays),[selected,setSelected]=useState(1);
 useEffect(()=>{setAuth(sessionStorage.getItem(AUTH)==="yes");setDays(loadDays());const q=new URLSearchParams(location.search).get("day");if(q)setSelected(Number(q))},[]);
 const data=days.find(d=>d.day===selected)||days[0];
 const update=(patch:Partial<TripDay>)=>setDays(p=>p.map(d=>d.day===selected?{...d,...patch}:d));
 const login=()=>{const expected=process.env.NEXT_PUBLIC_ADMIN_PASSWORD||"stone2026";if(password===expected){sessionStorage.setItem(AUTH,"yes");setAuth(true);setError("")}else setError("비밀번호가 맞지 않습니다.")};
 const strings=(title:string,items:string[],key:"highlights"|"checklist")=><><h2 className="sectionTitle">{title}</h2>{items.map((x,i)=><div className="editor" key={i}><input value={x} onChange={e=>update({[key]:items.map((v,n)=>n===i?e.target.value:v)})}/><button className="btn danger" onClick={()=>update({[key]:items.filter((_,n)=>n!==i)})}>삭제</button></div>)}<button className="btn soft" onClick={()=>update({[key]:[...items,"새 항목"]})}>+ 추가</button></>;
 if(!auth)return <main className="login"><section className="loginBox"><div className="brand">STONE&apos;S TRIPS</div><h1>관리자 로그인</h1><p className="small">Stage 3 상세정보를 수정합니다.</p><div className="form"><input type="password" value={password} placeholder="관리자 비밀번호" onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&login()}/><button className="btn primary" onClick={login}>로그인</button>{error&&<div className="error">{error}</div>}<Link className="btn soft" href="/">여행 홈으로</Link></div></section></main>;
 return <main className="shell"><header className="top"><Link className="btn soft" href={`/day/${selected}`}>미리보기</Link><div className="brand">STAGE 3 EDITOR</div><button className="btn soft" onClick={()=>{sessionStorage.removeItem(AUTH);setAuth(false)}}>로그아웃</button></header><section className="content"><h1>여행 상세정보 수정</h1><div className="notice">필요한 항목만 고친 뒤 전체 변경 저장을 누르세요.</div>
 <div className="form" style={{marginTop:16}}><label>수정할 DAY<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{days.map(d=><option value={d.day} key={d.day}>DAY {d.day} · {d.title}</option>)}</select></label>
 {([['date','날짜'],['title','화면 제목'],['subtitle','영문 부제'],['heroImage','대표사진 URL']] as const).map(([k,l])=><label key={k}>{l}<input value={data[k]} onChange={e=>update({[k]:e.target.value})}/></label>)}
 {([['summary','한줄 설명'],['route','오늘의 경로'],['transport','교통 안내'],['tip','여행 TIP'],['mapUrl','전체 지도 URL'],['notes','개인 메모']] as const).map(([k,l])=><label key={k}>{l}<textarea value={data[k]} onChange={e=>update({[k]:e.target.value})}/></label>)}</div>
 {strings('핵심 관전 포인트',data.highlights,'highlights')}
 <h2 className="sectionTitle">시간별 일정</h2>{data.schedule.map((x,i)=><div className="editor" key={x.id}><div className="row"><input value={x.icon} onChange={e=>update({schedule:data.schedule.map((v,n)=>n===i?{...v,icon:e.target.value}:v)})}/><input value={x.time} onChange={e=>update({schedule:data.schedule.map((v,n)=>n===i?{...v,time:e.target.value}:v)})}/></div><input value={x.title} onChange={e=>update({schedule:data.schedule.map((v,n)=>n===i?{...v,title:e.target.value}:v)})}/><textarea value={x.description} onChange={e=>update({schedule:data.schedule.map((v,n)=>n===i?{...v,description:e.target.value}:v)})}/><button className="btn danger" onClick={()=>update({schedule:data.schedule.filter((_,n)=>n!==i)})}>삭제</button></div>)}<button className="btn soft" onClick={()=>update({schedule:[...data.schedule,{id:crypto.randomUUID(),time:"",title:"새 일정",description:"",icon:"📍"}]})}>+ 일정 추가</button>
 <h2 className="sectionTitle">맛집·카페</h2>{data.food.map((x,i)=><div className="editor" key={i}><input value={x.name} placeholder="이름" onChange={e=>update({food:data.food.map((v,n)=>n===i?{...v,name:e.target.value}:v)})}/><div className="row"><input value={x.type} placeholder="구분" onChange={e=>update({food:data.food.map((v,n)=>n===i?{...v,type:e.target.value}:v)})}/><input value={x.mapUrl} placeholder="지도 URL" onChange={e=>update({food:data.food.map((v,n)=>n===i?{...v,mapUrl:e.target.value}:v)})}/></div><textarea value={x.note} onChange={e=>update({food:data.food.map((v,n)=>n===i?{...v,note:e.target.value}:v)})}/><button className="btn danger" onClick={()=>update({food:data.food.filter((_,n)=>n!==i)})}>삭제</button></div>)}<button className="btn soft" onClick={()=>update({food:[...data.food,{name:"새 장소",type:"",note:"",mapUrl:""}]})}>+ 맛집 추가</button>
 <h2 className="sectionTitle">예약정보</h2>{data.reservations.map((x,i)=><div className="editor" key={i}><input value={x.name} placeholder="예약명" onChange={e=>update({reservations:data.reservations.map((v,n)=>n===i?{...v,name:e.target.value}:v)})}/><div className="row"><input value={x.time} placeholder="시간" onChange={e=>update({reservations:data.reservations.map((v,n)=>n===i?{...v,time:e.target.value}:v)})}/><input value={x.code} placeholder="예약번호" onChange={e=>update({reservations:data.reservations.map((v,n)=>n===i?{...v,code:e.target.value}:v)})}/></div><textarea value={x.note} onChange={e=>update({reservations:data.reservations.map((v,n)=>n===i?{...v,note:e.target.value}:v)})}/><button className="btn danger" onClick={()=>update({reservations:data.reservations.filter((_,n)=>n!==i)})}>삭제</button></div>)}<button className="btn soft" onClick={()=>update({reservations:[...data.reservations,{name:"새 예약",time:"",code:"",note:""}]})}>+ 예약 추가</button>
 <h2 className="sectionTitle">예상비용</h2>{data.budget.map((x,i)=><div className="editor" key={i}><div className="row"><input value={x.label} onChange={e=>update({budget:data.budget.map((v,n)=>n===i?{...v,label:e.target.value}:v)})}/><input value={x.amount} onChange={e=>update({budget:data.budget.map((v,n)=>n===i?{...v,amount:e.target.value}:v)})}/></div><button className="btn danger" onClick={()=>update({budget:data.budget.filter((_,n)=>n!==i)})}>삭제</button></div>)}<button className="btn soft" onClick={()=>update({budget:[...data.budget,{label:"새 비용",amount:""}]})}>+ 비용 추가</button>
 {strings('체크리스트',data.checklist,'checklist')}
 <div className="actions" style={{marginTop:26}}><button className="btn primary" onClick={()=>{saveDays(days);setSaved(true);setTimeout(()=>setSaved(false),2200)}}>전체 변경 저장</button><button className="btn danger" onClick={()=>{if(confirm('모든 내용을 초기화할까요?')){resetDays();setDays(defaultDays)}}}>전체 기본값 복원</button><Link className="btn soft" href={`/day/${selected}`}>DAY {selected} 확인</Link></div>{saved&&<div className="notice" style={{marginTop:12}}>저장되었습니다.</div>}</section></main>
}
